--SELECT * FROM TABELA_DE_CLIENTES;

--SELECT NOME AS [NOME CLIENTE], CPF AS ID, BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

-- USANDO ALIAS NO NOME DA TABELA
--SELECT NOME AS [NOME CLIENTE], CPF AS ID, BAIRRO, CIDADE FROM TABELA_DE_CLIENTES TDC;

--SELECT * FROM NOTAS_FISCAIS WHERE DATA_VENDA >= '2017-01-01' AND DATA_VENDA <= '2017-01-31';
SELECT * FROM NOTAS_FISCAIS WHERE DATA_VENDA BETWEEN '2017-01-01' AND '2017-01-31';

SELECT * FROM TABELA_DE_PRODUTOS;
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'MANGA' AND TAMANHO = '470 ML';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'MANGA' OR TAMANHO = '470 ML';

SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT (SABOR = 'MANGA' AND TAMANHO = '470 ML');
SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT (SABOR = 'MANGA' OR TAMANHO = '470 ML');

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'MANGA' OR SABOR = 'MELANCIA' OR SABOR = 'CEREJA';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN ('MANGA', 'MELANCIA', 'CEREJA');

SELECT * FROM TABELA_DE_PRODUTOS WHERE( SABOR IN ('MANGA', 'MELANCIA', 'CEREJA')) AND EMBALAGEM = 'LATA';

SELECT * FROM TABELA_DE_PRODUTOS;
SELECT * FROM TABELA_DE_PRODUTOS WHERE NOME_DO_PRODUTO LIKE '%LARANJA%';

SELECT * FROM TABELA_DE_CLIENTES WHERE NOME LIKE '%SILVA%';