USE[SUCOS_VENDAS];

--CREATE DATABASE SUCO_VENDAS;

/*
CREATE TABLE TB_CLIENTES(
	[CPF] [CHAR] (11),
	[NOME] [VARCHAR] (100),
	[ENDERECO1] [VARCHAR] (150),
	[ENDERECO2] [VARCHAR] (150),
	[BAIRRO] [VARCHAR] (50),
	[CIDADE] [VARCHAR] (50),
	[ESTADO] [CHAR] (2),
	[CEP] [CHAR] (8),
	[DATA DE NASCIMENTO] [DATE],
	[IDADE] [SMALLINT],
	[GENERO] [CHAR] (1),
	[LIMITE DE CREDITO] [MONEY],
	[VOLUME DE COMPRA] [FLOAT],
	[PRIMEIRA COMPRA] [BIT]
);*/

--DROP TABLE [TB_PRODUTOS2];

/*
CREATE TABLE TB_VENDEDORES(
	[MATRICULA] [VARCHAR] (5),
	[NOME VENDEDOR] [VARCHAR] (100),
	[PERCENTUAL COMISSAO] [FLOAT],
);
*/

/*
INSERT INTO [TB_VENDEDORES](
	[MATRICULA],
	[NOME VENDEDOR],
	[PERCENTUAL COMISSAO]
)
VALUES(
	'00235',
	'Márcio Almeida Silva',
	8.00
);

*/

/*
UPDATE [TB_VENDEDORES]
SET [PERCENTUAL COMISSAO] = 0.08
WHERE [MATRICULA] = '00235';

SELECT * FROM [TB_VENDEDORES];

*/

/*
CREATE TABLE TB_PRODUTOS(
	[CODIGO PRODUTO] [VARCHAR] (20),
	[NOME PRODUTO] [VARCHAR] (150),
	[EMBALAGEM] [VARCHAR] (50),
	[TAMANHO] [VARCHAR] (100),
	[SABOR] [VARCHAR] (50),
	[PRECO LISTA] [SMALLMONEY]
);
*/

/*
INSERT INTO [TB_PRODUTOS](
	[CODIGO PRODUTO],
	[NOME PRODUTO],
	[EMBALAGEM],
	[TAMANHO],
	[SABOR],
	[PRECO LISTA]
)
VALUES(
	'1040107',
	'Light - 350 ml - Melância',
	'Lata',
	'350 ml',
	'Melância',
	4.56
);
*/

/*
INSERT INTO [TB_PRODUTOS](
	[CODIGO PRODUTO],
	[NOME PRODUTO],
	[EMBALAGEM],
	[TAMANHO],
	[SABOR],
	[PRECO LISTA]
)
VALUES(
	'1037797',
	'Clean - 2 Litros - Laranja',
	'PET',
	'2 Litros',
	'Laranja',
	16.01
);

INSERT INTO [TB_PRODUTOS](
	[CODIGO PRODUTO],
	[NOME PRODUTO],
	[EMBALAGEM],
	[TAMANHO],
	[SABOR],
	[PRECO LISTA]
)
VALUES(
	'1000889',
	'Sabor da Montanha - 700 ml - Uva',
	'Garrafa',
	'700 ml',
	'Uva',
	6.31
);

*/
-- SE A ORDEM DOS VALORES RESPEITAR A ORDEM DAS COLUNAS NÃO PRECISA DECLARAR OS NOMES DOS CAMPOS
/*
INSERT INTO [TB_PRODUTOS]
VALUES(
	'1004327',
	'Videira do Campo - 1,5 Litros - Melância',
	'PET',
	'1,5 Litros',
	'Melância',
	19.51
);

*/

-- INSERIR MAIS DE UM VALOR NO MESMO COMANDO (MAIS PEFORMÁTICO)
/*
INSERT INTO [TB_PRODUTOS]
VALUES('1088126', 'Linha Citros - 1 Litro - Limão', 'PET', '1 Litro',	'Limão', 7),
	  ('544931', 'Frescor do Verão - 350 ml - Limão', 'Lata', '350 ml',	'Limão', 2.46);


SELECT * FROM [TB_PRODUTOS];
*/

/*
INSERT INTO [TB_VENDEDORES]
VALUES('00236', 'Cláudia Morais', 0.08),
	  ('00237', 'Marcela Ferreira', 0.09);
*/

/*
UPDATE [TB_VENDEDORES]
SET [PERCENTUAL COMISSAO] = 0.11
WHERE [MATRICULA] = '00235';

UPDATE [TB_VENDEDORES]
SET [NOME VENDEDOR] = 'Cláudia Morais Sousa'
WHERE [MATRICULA] = '00236';
*/

/*
DELETE FROM [TB_VENDEDORES]
WHERE [MATRICULA] = '00236';

--ADICIONA UMA PRIMARY KEY EM UMA TABELA JÁ CRIADA (CAMPO CRIADO INICIALMENTE PARA ACEITAR NULL)
ALTER TABLE [TB_VENDEDORES]
ALTER COLUMN [MATRICULA] [VARCHAR] (5) NOT NULL;

ALTER TABLE [TB_VENDEDORES]
ADD CONSTRAINT [PK_MATRICULA] PRIMARY KEY CLUSTERED ([MATRICULA]);

*/

--SELECT * FROM [TB_VENDEDORES];

/*
UPDATE [TB_PRODUTOS]
SET [PRECO LISTA] = 3
WHERE [CODIGO PRODUTO] = '544931';

UPDATE [TB_PRODUTOS]
SET [PRECO LISTA] = 7.5, [EMBALAGEM] = 'Garrafa'
WHERE [CODIGO PRODUTO] = '1088126';
*/

/*
DELETE FROM [TB_PRODUTOS]
WHERE [CODIGO PRODUTO] = '1004327';
*/

/*
INSERT INTO [TB_PRODUTOS]
VALUES('1078680', 'Frescor do Verão - 470 ml - Manga', 'Garrafa', '470 ml',	'Manga', 5.18);

DELETE FROM [TB_PRODUTOS]
WHERE [CODIGO PRODUTO] = '1078680';
*/

--ADICIONA UMA PRIMARY KEY EM UMA TABELA JÁ CRIADA (CAMPO CRIADO INICIALMENTE PARA ACEITAR NULL)
/*
ALTER TABLE [TB_PRODUTOS]
ALTER COLUMN [CODIGO PRODUTO] [VARCHAR] (20) NOT NULL;

ALTER TABLE [TB_PRODUTOS]
ADD CONSTRAINT [PK_CODIGO_PRODUTO] PRIMARY KEY CLUSTERED ([CODIGO PRODUTO]);
*/

/*
SELECT * FROM [TB_PRODUTOS];

ALTER TABLE [TB_CLIENTES]
ALTER COLUMN [CPF] [VARCHAR] (11) NOT NULL;

ALTER TABLE [TB_CLIENTES]
ADD CONSTRAINT [PK_CPF] PRIMARY KEY CLUSTERED ([CPF]);


INSERT INTO [TB_CLIENTES]
VALUES('00245670801', 'Joao da Silva', 'Rua Projetada A', 'Numero 233', 'Copacabana', 'Rio de Janeiro', 'RJ', '1329014', '1974-04-25', 57, 'M',
		200000, 2000.29, 1);

SELECT * FROM [TB_CLIENTES];
*/

/*
ALTER TABLE [TB_VENDEDORES]
ALTER COLUMN [PERCENTUAL COMISSAO] [FLOAT] NOT NULL;

ALTER TABLE [TB_VENDEDORES]
ADD [CIDADE] VARCHAR (100);

ALTER TABLE [TB_VENDEDORES]
ADD [DATA INICIO] DATE DEFAULT ('2023-01-01') NOT NULL;

ALTER TABLE [TB_VENDEDORES]
ADD [TEM_DEPENDENTE] BIT;

INSERT INTO [TB_VENDEDORES]
VALUES('00239', 'Alberto de Sá Verneck', 0.08, 'São Paulo', '2020-06-05', 1);

SELECT * FROM [TB_VENDEDORES];


INSERT INTO [TB_CLIENTES]
VALUES('00245670802', 'Maria da Silva', 'Rua Projetada A', 'Numero 233', 'Copacabana', 'Rio de Janeiro', 'RJ', '1329014', '1975-04-25', 47, 'M',
		200000, 2000.29, 'FALSE');

INSERT INTO [TB_CLIENTES]
VALUES('00345670802', 'Marcia da Silva', 'Rua Projetada A', 'Numero 233', 'Copacabana', 'Rio de Janeiro', 'RJ', '1329014', '1976-04-25', 47, 'M',
		200000, 2000.29, 'TRUE');

SELECT * FROM [TB_CLIENTES];



INSERT INTO [TB_VENDEDORES]
VALUES('00240', 'Marcela Almeida', 0.07, 'Rio de Janeiro', '2021-01-12', 'FALSE');

SELECT * FROM [TB_VENDEDORES];

INSERT INTO [TB_VENDEDORES]
VALUES('00241', 'João da Silva', 0.06, 'São Paulo', '2021-01-12', 'FALSE'),
	  ('00242', 'João da Silva', 0.07, 'Rio de Janeiro', '2021-01-12', 'FALSE'),
	  ('00243', 'Juliana Marques', 0.09, 'São Paulo', '2021-01-12', 'FALSE'),
	  ('00244', 'Pedro Gomes', 0.08, 'São Paulo', '2021-01-12', 'FALSE'),
	  ('00245', 'Christina Rodrigues', 0.07, 'Rio de Janeiro', '2021-01-12', 'FALSE');
*/

-- USANDO ALIAS
/*
SELECT [NOME] AS [NOME DO CLIENTE], [CPF] AS [DOCUMENTO] FROM [TB_CLIENTES];
SELECT [MATRICULA] AS [IDENTIFICADOR], [NOME VENDEDOR] AS [VENDEDOR] FROM [TB_VENDEDORES];
*/

/*
SELECT * FROM [TB_PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1078680';

SELECT * FROM [TB_PRODUTOS] WHERE [SABOR] = 'LIMÃO';

SELECT [MATRICULA] AS [IDENTIFICADOR], [NOME VENDEDOR] AS [VENDEDOR] FROM [TB_VENDEDORES] WHERE [CIDADE] = 'SÃO PAULO';


SELECT * FROM [TB_PRODUTOS] WHERE [EMBALAGEM] = 'Lata';
UPDATE [TB_PRODUTOS] SET [PRECO DE LISTA] = ([PRECO DE LISTA] * 1.1) WHERE [EMBALAGEM] = 'LATA';


UPDATE [TB_VENDEDORES] SET [DATA INICIO] = '2019-02-13' WHERE [MATRICULA] = '00245';

--UPDATE [TB_VENDEDORES] SET [PERCENTUAL COMISSAO] = ([PERCENTUAL COMISSAO] + 0.01) WHERE [TEM_DEPENDENTE] = 'TRUE';
SELECT * FROM [TB_VENDEDORES];
*/

-- O OPERADOR < E > QUANDO USADOS EM STRING USAM A ORDEM ALFABÉTICA PARA RETORNAR A CONSULTA
--SELECT * FROM [TB_PRODUTOS] WHERE [SABOR] > 'LIMÃO';

-- SELECT * FROM [TB_VENDEDORES] WHERE [PERCENTUAL COMISSAO] < 0.08;

-- TRABALHANDO COM DATAS
/*
SELECT * FROM [TB_CLIENTES] WHERE [DATA DE NASCIMENTO] < '1995-09-11';

SELECT * FROM [TB_CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) = 1995;

SELECT [NOME], YEAR([DATA DE NASCIMENTO]) AS [ANO NASCIMENTO] FROM [TB_CLIENTES];

SELECT [NOME], YEAR([DATA DE NASCIMENTO]) AS [ANO NASCIMENTO], MONTH([DATA DE NASCIMENTO]) AS [MÊS NASCIMENTO], DAY([DATA DE NASCIMENTO]) AS [DIA NASCIMENTO] FROM [TB_CLIENTES];

SELECT * FROM [TB_VENDEDORES] WHERE YEAR([DATA INICIO]) <= 2020;
*/

-- SELECT * FROM [TB_VENDEDORES] WHERE YEAR([DATA INICIO]) <= 2020 AND [CIDADE] = 'SÃO PAULO';

SELECT * FROM [TB_PRODUTOS];