-- CREATE DATABASE SUCO_VENDAS;

/*
CREATE TABLE TB_CLIENTES(
	[CPF] [CHAR] (11),
	[NOME] [VARCHAR] (100),
	[ENDERECO1] [VARCHAR] (150),
	[ENDERECO2] [VARCHAR] (150),
	[BAIRRO] [VARCHAR] (50),
	[CIDADE] [VARCHAR] (50),
	[ESTADO] [CHAR] (2),
	[CEP] [CHAR] (8),
	[DATA DE NASCIMENTO] [DATE],
	[IDADE] [SMALLINT],
	[GENERO] [CHAR] (1),
	[LIMITE DE CREDITO] [MONEY],
	[VOLUME DE COMPRA] [FLOAT],
	[PRIMEIRA COMPRA] [BIT]
);*/

-- DROP TABLE [TB_CLIENTES2];

/*
CREATE TABLE TB_VENDEDORES(
	[MATRICULA] [VARCHAR] (5),
	[NOME VENDEDOR] [VARCHAR] (100),
	[PERCENTUAL COMISSAO] [FLOAT],
);
*/

CREATE TABLE TB_PRODUTOS(
	[CODIGO PRODUTO] [VARCHAR] (20),
	[NOME PRODUTO] [VARCHAR] (150),
	[EMBALAGEM] [VARCHAR] (50),
	[TAMANHO] [VARCHAR] (100),
	[SABOR] [VARCHAR] (50),
	[PRECO LISTA] [SMALLMONEY]
);

