USE[SUCOS_VENDAS];

--CREATE DATABASE SUCO_VENDAS;

/*
CREATE TABLE TB_CLIENTES(
	[CPF] [CHAR] (11),
	[NOME] [VARCHAR] (100),
	[ENDERECO1] [VARCHAR] (150),
	[ENDERECO2] [VARCHAR] (150),
	[BAIRRO] [VARCHAR] (50),
	[CIDADE] [VARCHAR] (50),
	[ESTADO] [CHAR] (2),
	[CEP] [CHAR] (8),
	[DATA DE NASCIMENTO] [DATE],
	[IDADE] [SMALLINT],
	[GENERO] [CHAR] (1),
	[LIMITE DE CREDITO] [MONEY],
	[VOLUME DE COMPRA] [FLOAT],
	[PRIMEIRA COMPRA] [BIT]
);*/

--DROP TABLE [TB_PRODUTOS2];

/*
CREATE TABLE TB_VENDEDORES(
	[MATRICULA] [VARCHAR] (5),
	[NOME VENDEDOR] [VARCHAR] (100),
	[PERCENTUAL COMISSAO] [FLOAT],
);
*/

/*
INSERT INTO [TB_VENDEDORES](
	[MATRICULA],
	[NOME VENDEDOR],
	[PERCENTUAL COMISSAO]
)
VALUES(
	'00235',
	'Márcio Almeida Silva',
	8.00
);

*/

/*
UPDATE [TB_VENDEDORES]
SET [PERCENTUAL COMISSAO] = 0.08
WHERE [MATRICULA] = '00235';

SELECT * FROM [TB_VENDEDORES];

*/

/*
CREATE TABLE TB_PRODUTOS(
	[CODIGO PRODUTO] [VARCHAR] (20),
	[NOME PRODUTO] [VARCHAR] (150),
	[EMBALAGEM] [VARCHAR] (50),
	[TAMANHO] [VARCHAR] (100),
	[SABOR] [VARCHAR] (50),
	[PRECO LISTA] [SMALLMONEY]
);
*/

/*
INSERT INTO [TB_PRODUTOS](
	[CODIGO PRODUTO],
	[NOME PRODUTO],
	[EMBALAGEM],
	[TAMANHO],
	[SABOR],
	[PRECO LISTA]
)
VALUES(
	'1040107',
	'Light - 350 ml - Melância',
	'Lata',
	'350 ml',
	'Melância',
	4.56
);
*/

/*
INSERT INTO [TB_PRODUTOS](
	[CODIGO PRODUTO],
	[NOME PRODUTO],
	[EMBALAGEM],
	[TAMANHO],
	[SABOR],
	[PRECO LISTA]
)
VALUES(
	'1037797',
	'Clean - 2 Litros - Laranja',
	'PET',
	'2 Litros',
	'Laranja',
	16.01
);

INSERT INTO [TB_PRODUTOS](
	[CODIGO PRODUTO],
	[NOME PRODUTO],
	[EMBALAGEM],
	[TAMANHO],
	[SABOR],
	[PRECO LISTA]
)
VALUES(
	'1000889',
	'Sabor da Montanha - 700 ml - Uva',
	'Garrafa',
	'700 ml',
	'Uva',
	6.31
);

*/
-- SE A ORDEM DOS VALORES RESPEITAR A ORDEM DAS COLUNAS NÃO PRECISA DECLARAR OS NOMES DOS CAMPOS
/*
INSERT INTO [TB_PRODUTOS]
VALUES(
	'1004327',
	'Videira do Campo - 1,5 Litros - Melância',
	'PET',
	'1,5 Litros',
	'Melância',
	19.51
);

*/

-- INSERIR MAIS DE UM VALOR NO MESMO COMANDO (MAIS PEFORMÁTICO)
/*
INSERT INTO [TB_PRODUTOS]
VALUES('1088126', 'Linha Citros - 1 Litro - Limão', 'PET', '1 Litro',	'Limão', 7),
	  ('544931', 'Frescor do Verão - 350 ml - Limão', 'Lata', '350 ml',	'Limão', 2.46);


SELECT * FROM [TB_PRODUTOS];
*/

/*
INSERT INTO [TB_VENDEDORES]
VALUES('00236', 'Cláudia Morais', 0.08),
	  ('00237', 'Marcela Ferreira', 0.09);
*/

/*
UPDATE [TB_VENDEDORES]
SET [PERCENTUAL COMISSAO] = 0.11
WHERE [MATRICULA] = '00235';

UPDATE [TB_VENDEDORES]
SET [NOME VENDEDOR] = 'Cláudia Morais Sousa'
WHERE [MATRICULA] = '00236';
*/

/*
DELETE FROM [TB_VENDEDORES]
WHERE [MATRICULA] = '00236';

--ADICIONA UMA PRIMARY KEY EM UMA TABELA JÁ CRIADA (CAMPO CRIADO INICIALMENTE PARA ACEITAR NULL)
ALTER TABLE [TB_VENDEDORES]
ALTER COLUMN [MATRICULA] [VARCHAR] (5) NOT NULL;

ALTER TABLE [TB_VENDEDORES]
ADD CONSTRAINT [PK_MATRICULA] PRIMARY KEY CLUSTERED ([MATRICULA]);

*/

SELECT * FROM [TB_VENDEDORES];

/*
UPDATE [TB_PRODUTOS]
SET [PRECO LISTA] = 3
WHERE [CODIGO PRODUTO] = '544931';

UPDATE [TB_PRODUTOS]
SET [PRECO LISTA] = 7.5, [EMBALAGEM] = 'Garrafa'
WHERE [CODIGO PRODUTO] = '1088126';
*/

/*
DELETE FROM [TB_PRODUTOS]
WHERE [CODIGO PRODUTO] = '1004327';
*/

/*
INSERT INTO [TB_PRODUTOS]
VALUES('1078680', 'Frescor do Verão - 470 ml - Manga', 'Garrafa', '470 ml',	'Manga', 5.18);

DELETE FROM [TB_PRODUTOS]
WHERE [CODIGO PRODUTO] = '1078680';
*/

--ADICIONA UMA PRIMARY KEY EM UMA TABELA JÁ CRIADA (CAMPO CRIADO INICIALMENTE PARA ACEITAR NULL)
ALTER TABLE [TB_PRODUTOS]
ALTER COLUMN [CODIGO PRODUTO] [VARCHAR] (20) NOT NULL;

ALTER TABLE [TB_PRODUTOS]
ADD CONSTRAINT [PK_CODIGO_PRODUTO] PRIMARY KEY CLUSTERED ([CODIGO PRODUTO]);

SELECT * FROM [TB_PRODUTOS];