USE(SUCOS_VENDAS);

--CREATE DATABASE SUCO_VENDAS;

/*
CREATE TABLE TB_CLIENTES(
	[CPF] [CHAR] (11),
	[NOME] [VARCHAR] (100),
	[ENDERECO1] [VARCHAR] (150),
	[ENDERECO2] [VARCHAR] (150),
	[BAIRRO] [VARCHAR] (50),
	[CIDADE] [VARCHAR] (50),
	[ESTADO] [CHAR] (2),
	[CEP] [CHAR] (8),
	[DATA DE NASCIMENTO] [DATE],
	[IDADE] [SMALLINT],
	[GENERO] [CHAR] (1),
	[LIMITE DE CREDITO] [MONEY],
	[VOLUME DE COMPRA] [FLOAT],
	[PRIMEIRA COMPRA] [BIT]
);*/

--DROP TABLE [TB_PRODUTOS2];

/*
CREATE TABLE TB_VENDEDORES(
	[MATRICULA] [VARCHAR] (5),
	[NOME VENDEDOR] [VARCHAR] (100),
	[PERCENTUAL COMISSAO] [FLOAT],
);
*/

/*
INSERT INTO [TB_VENDEDORES](
	[MATRICULA],
	[NOME VENDEDOR],
	[PERCENTUAL COMISSAO]
)
VALUES(
	'00235',
	'Márcio Almeida Silva',
	8.00
);

*/

/*
UPDATE [TB_VENDEDORES]
SET [PERCENTUAL COMISSAO] = 0.08
WHERE [MATRICULA] = '00235';

SELECT * FROM [TB_VENDEDORES];

*/

/*
CREATE TABLE TB_PRODUTOS(
	[CODIGO PRODUTO] [VARCHAR] (20),
	[NOME PRODUTO] [VARCHAR] (150),
	[EMBALAGEM] [VARCHAR] (50),
	[TAMANHO] [VARCHAR] (100),
	[SABOR] [VARCHAR] (50),
	[PRECO LISTA] [SMALLMONEY]
);
*/

/*
INSERT INTO [TB_PRODUTOS](
	[CODIGO PRODUTO],
	[NOME PRODUTO],
	[EMBALAGEM],
	[TAMANHO],
	[SABOR],
	[PRECO LISTA]
)
VALUES(
	'1040107',
	'Light - 350 ml - Melância',
	'Lata',
	'350 ml',
	'Melância',
	4.56
);
*/

--SELECT * FROM [TB_PRODUTOS];

INSERT INTO [TB_PRODUTOS](
	[CODIGO PRODUTO],
	[NOME PRODUTO],
	[EMBALAGEM],
	[TAMANHO],
	[SABOR],
	[PRECO LISTA]
)
VALUES(
	'1037797',
	'Clean - 2 Litros - Laranja',
	'PET',
	'2 Litros',
	'Laranja',
	16.01
);

INSERT INTO [TB_PRODUTOS](
	[CODIGO PRODUTO],
	[NOME PRODUTO],
	[EMBALAGEM],
	[TAMANHO],
	[SABOR],
	[PRECO LISTA]
)
VALUES(
	'1000889',
	'Sabor da Montanha - 700 ml - Uva',
	'Garrafa',
	'700 ml',
	'Uva',
	6.31
);

SELECT * FROM [TB_PRODUTOS];